In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import pandas as pd
import numpy as np
data=pd.read_table("/content/drive/MyDrive/ROCo/test/radiology/captions.txt")
data

,ROCO_00001,Axial MRI (coronal view).
0,ROCO_00006,Coronal plain computed tomography image showi...
1,ROCO_00016,Axial source image from an intracranial magne...
2,ROCO_00025,"The apical height, homogeneity, and the thick..."
3,ROCO_00031,CTO of RCA (closure in the 2nd segment)
4,ROCO_00036,Venography shows a large amount of thrombogen...
...,...,...
8173,ROCO_81771,Damus–Kaye–Stansel shunt. Oblique coronal MIP...
8174,ROCO_81778,"MRI pelvis post-radiation, axial STIR/T2W FSE..."
8175,ROCO_81792,Fluoroscopic image showing attempts to grab t...
8176,ROCO_81796,Positron emission tomography–computed tomogra...


In [4]:
data.columns=['label','caption']
data.head()

,label,caption
0,ROCO_00006,Coronal plain computed tomography image showi...
1,ROCO_00016,Axial source image from an intracranial magne...
2,ROCO_00025,"The apical height, homogeneity, and the thick..."
3,ROCO_00031,CTO of RCA (closure in the 2nd segment)
4,ROCO_00036,Venography shows a large amount of thrombogen...


In [5]:
captions = " ".join(data['caption'])
print(captions[:500])

 Coronal plain computed tomography image showing multiple large tumor masses with edge enhancement inside the abdominal cavity and liver.  Axial source image from an intracranial magnetic resonance angiogram reveals abnormal arterial signal elevation in the left more than right cavernous sinuses consistent with a carotid cavernous fistula, as indicated by the arrow.  The apical height, homogeneity, and the thickness of mineral trioxide aggregate plug  CTO of RCA (closure in the 2nd segment)  Ven


In [6]:
captions=captions.lower()

In [7]:
from nltk.corpus import stopwords
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [8]:
stop_words=set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [9]:
text_input = " ".join([word.lower() for word in captions.split() if word.lower() not in stop_words][:500])
text_input

"coronal plain computed tomography image showing multiple large tumor masses edge enhancement inside abdominal cavity liver. axial source image intracranial magnetic resonance angiogram reveals abnormal arterial signal elevation left right cavernous sinuses consistent carotid cavernous fistula, indicated arrow. apical height, homogeneity, thickness mineral trioxide aggregate plug cto rca (closure 2nd segment) venography shows large amount thrombogenesis femoropoplitea vein thrombolysis. postoperative decreased size cyst fetal aortic arch. solid arrow represents ascending aorta dotted arrow represents aortic arch distal ductus arteriosus. note aliasing ductal arch reflecting turbulent blood flow result external compression due mass-effect. abdominal computed tomography scan. arrow points likely cholecystocutaneous fistulous track. distension digestive avec niveaux hydro-aériques coliques et vacuité pelvienne panoramic x ray taken four years later showing unilocular radiolucent area left

In [10]:
from textblob import TextBlob
TextBlob(text_input).correct()

TextBlob("corona plain computer cosmography image showing multiple large tumor masses edge enhancement inside abdominal cavity liver. animal source image intracranial magnetic resonance angiogram reveals abnormal arterial signal elevation left right cavernous sinuses consistent carotid cavernous fistula, indicated arrow. capital height, homogeneity, thickness mineral dioxide aggregate plug to sca (closure and segment) geography shows large amount thrombogenesis femoropoplitea vein thrombosis. postoperative decreased size cyst fatal aortic arch. solid arrow represents ascending aorta dotted arrow represents aortic arch distal ducts arterioles. note arising distal arch reflecting turbulent blood flow result external compression due mass-effect. abdominal computer cosmography scan. arrow points likely cholecystocutaneous fistulas track. distension digestive avec niveaux hydra-aériques cosaques et vacuité pelvienne panorama x ray taken four years later showing unilocular radiolucent area l

In [11]:
from nltk.tokenize import sent_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [12]:
sent_tokenize(text_input)

['coronal plain computed tomography image showing multiple large tumor masses edge enhancement inside abdominal cavity liver.',
 'axial source image intracranial magnetic resonance angiogram reveals abnormal arterial signal elevation left right cavernous sinuses consistent carotid cavernous fistula, indicated arrow.',
 'apical height, homogeneity, thickness mineral trioxide aggregate plug cto rca (closure 2nd segment) venography shows large amount thrombogenesis femoropoplitea vein thrombolysis.',
 'postoperative decreased size cyst fetal aortic arch.',
 'solid arrow represents ascending aorta dotted arrow represents aortic arch distal ductus arteriosus.',
 'note aliasing ductal arch reflecting turbulent blood flow result external compression due mass-effect.',
 'abdominal computed tomography scan.',
 'arrow points likely cholecystocutaneous fistulous track.',
 'distension digestive avec niveaux hydro-aériques coliques et vacuité pelvienne panoramic x ray taken four years later showing

In [13]:
from nltk.tokenize import wordpunct_tokenize
wordpunct_tokenize(text_input)

['coronal',
 'plain',
 'computed',
 'tomography',
 'image',
 'showing',
 'multiple',
 'large',
 'tumor',
 'masses',
 'edge',
 'enhancement',
 'inside',
 'abdominal',
 'cavity',
 'liver',
 '.',
 'axial',
 'source',
 'image',
 'intracranial',
 'magnetic',
 'resonance',
 'angiogram',
 'reveals',
 'abnormal',
 'arterial',
 'signal',
 'elevation',
 'left',
 'right',
 'cavernous',
 'sinuses',
 'consistent',
 'carotid',
 'cavernous',
 'fistula',
 ',',
 'indicated',
 'arrow',
 '.',
 'apical',
 'height',
 ',',
 'homogeneity',
 ',',
 'thickness',
 'mineral',
 'trioxide',
 'aggregate',
 'plug',
 'cto',
 'rca',
 '(',
 'closure',
 '2nd',
 'segment',
 ')',
 'venography',
 'shows',
 'large',
 'amount',
 'thrombogenesis',
 'femoropoplitea',
 'vein',
 'thrombolysis',
 '.',
 'postoperative',
 'decreased',
 'size',
 'cyst',
 'fetal',
 'aortic',
 'arch',
 '.',
 'solid',
 'arrow',
 'represents',
 'ascending',
 'aorta',
 'dotted',
 'arrow',
 'represents',
 'aortic',
 'arch',
 'distal',
 'ductus',
 'arterios

In [14]:
from nltk.tokenize import TreebankWordTokenizer
tokenizer=TreebankWordTokenizer()
tokenizer.tokenize(text_input)

['coronal',
 'plain',
 'computed',
 'tomography',
 'image',
 'showing',
 'multiple',
 'large',
 'tumor',
 'masses',
 'edge',
 'enhancement',
 'inside',
 'abdominal',
 'cavity',
 'liver.',
 'axial',
 'source',
 'image',
 'intracranial',
 'magnetic',
 'resonance',
 'angiogram',
 'reveals',
 'abnormal',
 'arterial',
 'signal',
 'elevation',
 'left',
 'right',
 'cavernous',
 'sinuses',
 'consistent',
 'carotid',
 'cavernous',
 'fistula',
 ',',
 'indicated',
 'arrow.',
 'apical',
 'height',
 ',',
 'homogeneity',
 ',',
 'thickness',
 'mineral',
 'trioxide',
 'aggregate',
 'plug',
 'cto',
 'rca',
 '(',
 'closure',
 '2nd',
 'segment',
 ')',
 'venography',
 'shows',
 'large',
 'amount',
 'thrombogenesis',
 'femoropoplitea',
 'vein',
 'thrombolysis.',
 'postoperative',
 'decreased',
 'size',
 'cyst',
 'fetal',
 'aortic',
 'arch.',
 'solid',
 'arrow',
 'represents',
 'ascending',
 'aorta',
 'dotted',
 'arrow',
 'represents',
 'aortic',
 'arch',
 'distal',
 'ductus',
 'arteriosus.',
 'note',
 'ali

In [16]:
from nltk.stem import PorterStemmer

In [17]:
stemming=PorterStemmer()

In [18]:
for word in captions:
  print(word+"---"+stemming.stem(word))

Streaming output truncated to the last 5000 lines.
:---:
 --- 
n---n
o---o
t---t
e---e
 --- 
p---p
e---e
r---r
i---i
v---v
e---e
n---n
t---t
r---r
i---i
c---c
u---u
l---l
a---a
r---r
 --- 
h---h
y---y
p---p
e---e
r---r
i---i
n---n
t---t
e---e
n---n
s---s
i---i
t---t
i---i
e---e
s---s
 --- 
i---i
n---n
 --- 
r---r
e---e
l---l
a---a
t---t
i---i
o---o
n---n
 --- 
w---w
i---i
t---t
h---h
 --- 
c---c
s---s
f---f
 --- 
r---r
e---e
s---s
o---o
r---r
p---p
t---t
i---i
o---o
n---n
.---.
 --- 
 --- 
r---r
a---a
d---d
i---i
o---o
g---g
r---r
a---a
p---p
h---h
 --- 
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 --- 
t---t
r---r
o---o
n---n
z---z
o---o
 --- 
t---t
y---y
p---p
e---e
 --- 
v---v
 --- 
t---t
r---r
a---a
n---n
s---s
t---t
r---r
o---o
c---c
h---h
a---a
n---n
t---t
e---e
r---r
i---i
c---c
 --- 
f---f
r---r
a---a
c---c
t---t
u---u
r---r
e---e
.---.
 --- 
 --- 
m---m
a---a
g---g
n---n
e---e
t---t
i---i
c---c
 --- 
r---r
e---e
s---s
o---o
n---n
a---a
n---n
c---c
e---e
 --- 
i---i
m---m
a---a
g

In [19]:
from nltk.stem import RegexpStemmer

In [22]:
reg_stemmer=RegexpStemmer("tion$|e$|s$|able$|graphy$")

In [23]:
reg_stemmer.stem("calculation")

'calcula'

In [24]:
from nltk.stem import SnowballStemmer

In [25]:
snowballstemmer=SnowballStemmer('english')

In [26]:
for word in captions:
  print(word+"---"+snowballstemmer.stem(word))

Streaming output truncated to the last 5000 lines.
:---:
 --- 
n---n
o---o
t---t
e---e
 --- 
p---p
e---e
r---r
i---i
v---v
e---e
n---n
t---t
r---r
i---i
c---c
u---u
l---l
a---a
r---r
 --- 
h---h
y---y
p---p
e---e
r---r
i---i
n---n
t---t
e---e
n---n
s---s
i---i
t---t
i---i
e---e
s---s
 --- 
i---i
n---n
 --- 
r---r
e---e
l---l
a---a
t---t
i---i
o---o
n---n
 --- 
w---w
i---i
t---t
h---h
 --- 
c---c
s---s
f---f
 --- 
r---r
e---e
s---s
o---o
r---r
p---p
t---t
i---i
o---o
n---n
.---.
 --- 
 --- 
r---r
a---a
d---d
i---i
o---o
g---g
r---r
a---a
p---p
h---h
 --- 
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 --- 
t---t
r---r
o---o
n---n
z---z
o---o
 --- 
t---t
y---y
p---p
e---e
 --- 
v---v
 --- 
t---t
r---r
a---a
n---n
s---s
t---t
r---r
o---o
c---c
h---h
a---a
n---n
t---t
e---e
r---r
i---i
c---c
 --- 
f---f
r---r
a---a
c---c
t---t
u---u
r---r
e---e
.---.
 --- 
 --- 
m---m
a---a
g---g
n---n
e---e
t---t
i---i
c---c
 --- 
r---r
e---e
s---s
o---o
n---n
a---a
n---n
c---c
e---e
 --- 
i---i
m---m
a---a
g

In [27]:
stemming.stem("calculation"),snowballstemmer.stem("calculation")

('calcul', 'calcul')

In [28]:
from nltk.stem import WordNetLemmatizer
import nltk

In [29]:
nltk.download("wordnet")

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [30]:
lemmatizer=WordNetLemmatizer()

In [31]:
lemmatizer.lemmatize("corpora",pos="n")

'corpus'

In [32]:
import nltk
nltk.download("punkt")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [33]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [34]:
from nltk.stem import PorterStemmer
stemmer=PorterStemmer()

In [35]:
sentences=nltk.sent_tokenize(captions)

In [36]:
nltk.download("stopwords")
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [37]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [38]:
for i in range(len(sentences)):
    words=nltk.word_tokenize(sentences[i])
    words=[stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i]=" ".join(words)

In [39]:
print(sentences)

['coron plain comput tomographi imag show multipl larg tumor mass edg enhanc insid abdomin caviti liver .', 'axial sourc imag intracrani magnet reson angiogram reveal abnorm arteri signal elev left right cavern sinus consist carotid cavern fistula , indic arrow .', 'apic height , homogen , thick miner trioxid aggreg plug cto rca ( closur 2nd segment ) venographi show larg amount thrombogenesi femoropoplitea vein thrombolysi .', 'postop decreas size cyst fetal aortic arch .', 'solid arrow repres ascend aorta dot arrow repres aortic arch distal ductu arteriosu .', 'note alias ductal arch reflect turbul blood flow result extern compress due mass-effect .', 'abdomin comput tomographi scan .', 'arrow point like cholecystocutan fistul track .', 'distens digest avec niveaux hydro-aériqu coliqu et vacuité pelvienn panoram x ray taken four year later show unilocular radioluc area left ramu .', 'anteroposterior radiograph pelvi recent follow .', 'immedi postinjuri magnet reson imag demonstr inta

In [40]:
for i in range(len(sentences)):
    words=nltk.word_tokenize(sentences[i])
    words=[snowballstemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i]=" ".join(words)

In [41]:
sentences

['coron plain comput tomographi imag show multipl larg tumor mass edg enhanc insid abdomin caviti liver .',
 'axial sourc imag intracrani magnet reson angiogram reveal abnorm arteri signal elev left right cavern sinus consist carotid cavern fistula , indic arrow .',
 'apic height , homogen , thick miner trioxid aggreg plug cto rca ( closur 2nd segment ) venographi show larg amount thrombogenesi femoropoplitea vein thrombolysi .',
 'postop decrea size cyst fetal aortic arch .',
 'solid arrow repr ascend aorta dot arrow repr aortic arch distal ductu arteriosu .',
 'note alia ductal arch reflect turbul blood flow result extern compress due mass-effect .',
 'abdomin comput tomographi scan .',
 'arrow point like cholecystocutan fistul track .',
 'disten digest avec niveaux hydro-aériqu coliqu et vacuité pelvienn panoram x ray taken four year later show unilocular radioluc area left ramu .',
 'anteroposterior radiograph pelvi recent follow .',
 'immedi postinjuri magnet reson imag demonstr i

In [42]:
import nltk
nltk.download("avergaed_perceptron_tagger")

[nltk_data] Error loading avergaed_perceptron_tagger: Package
[nltk_data]     'avergaed_perceptron_tagger' not found in index


False

In [43]:
sentences

['coron plain comput tomographi imag show multipl larg tumor mass edg enhanc insid abdomin caviti liver .',
 'axial sourc imag intracrani magnet reson angiogram reveal abnorm arteri signal elev left right cavern sinus consist carotid cavern fistula , indic arrow .',
 'apic height , homogen , thick miner trioxid aggreg plug cto rca ( closur 2nd segment ) venographi show larg amount thrombogenesi femoropoplitea vein thrombolysi .',
 'postop decrea size cyst fetal aortic arch .',
 'solid arrow repr ascend aorta dot arrow repr aortic arch distal ductu arteriosu .',
 'note alia ductal arch reflect turbul blood flow result extern compress due mass-effect .',
 'abdomin comput tomographi scan .',
 'arrow point like cholecystocutan fistul track .',
 'disten digest avec niveaux hydro-aériqu coliqu et vacuité pelvienn panoram x ray taken four year later show unilocular radioluc area left ramu .',
 'anteroposterior radiograph pelvi recent follow .',
 'immedi postinjuri magnet reson imag demonstr i

In [44]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.


True

In [45]:
for i in range(len(sentences)):
      words=nltk.word_tokenize(sentences[i])
      pos_tag=nltk.pos_tag(words)
      print(pos_tag)

Streaming output truncated to the last 5000 lines.
[('intern', 'JJ'), ('bright', 'JJ'), ('signal', 'NN'), ('inferior', 'NN'), ('rectu', 'NN'), ('muscle.a', 'NN'), ('high', 'JJ'), ('inten', 'JJ'), ('area', 'NN'), ('inferior', 'JJ'), ('rectu', 'NN'), ('muscl', 'NN'), ('measur', 'VBD'), ('t1-weight', 'JJ'), ('coron', 'NN'), ('magnet', 'NN'), ('reson', 'NN'), ('imag', 'NN'), ('(', '('), ('arrow', 'NN'), (')', ')'), ('.', '.')]
[('later', 'RB'), ('view', 'NN'), ('x-ray', 'JJ'), ('lumbar', 'NN'), ('spine', 'NN'), ('fal', 'NN'), ('aneurysm', 'NN'), ('segment', 'NN'), ('arteri', 'NN'), ('left', 'VBD'), ('lobe', 'NN'), ('.', '.')]
[('pulmonari', 'NN'), ('angiographi', 'NN'), ('hemoptysi', 'NN'), ('present', 'JJ'), ('extrava', 'NN'), ('contrast', 'NN'), ('media', 'NNS'), ('segment', 'NN'), ('arteri', 'NN'), ('left', 'VBD'), ('lobe', 'JJ'), ('format', 'JJ'), ('fal', 'NN'), ('aneurysm', 'NN'), ('.', '.')]
[('56-year-old', 'JJ'), ('woman', 'NN'), ('present', 'JJ'), ('emerg', 'JJ'), ('depart', 'NN')

In [46]:
words=nltk.word_tokenize(captions)

In [47]:
nltk.download("maxent_ne_chunker")
nltk.download("words")

[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.


True

In [48]:
from nltk import ne_chunk

In [49]:
nltk.download('maxent_ne_chunker_tab')

[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker_tab.zip.


True

In [50]:
words

['coronal',
 'plain',
 'computed',
 'tomography',
 'image',
 'showing',
 'multiple',
 'large',
 'tumor',
 'masses',
 'with',
 'edge',
 'enhancement',
 'inside',
 'the',
 'abdominal',
 'cavity',
 'and',
 'liver',
 '.',
 'axial',
 'source',
 'image',
 'from',
 'an',
 'intracranial',
 'magnetic',
 'resonance',
 'angiogram',
 'reveals',
 'abnormal',
 'arterial',
 'signal',
 'elevation',
 'in',
 'the',
 'left',
 'more',
 'than',
 'right',
 'cavernous',
 'sinuses',
 'consistent',
 'with',
 'a',
 'carotid',
 'cavernous',
 'fistula',
 ',',
 'as',
 'indicated',
 'by',
 'the',
 'arrow',
 '.',
 'the',
 'apical',
 'height',
 ',',
 'homogeneity',
 ',',
 'and',
 'the',
 'thickness',
 'of',
 'mineral',
 'trioxide',
 'aggregate',
 'plug',
 'cto',
 'of',
 'rca',
 '(',
 'closure',
 'in',
 'the',
 '2nd',
 'segment',
 ')',
 'venography',
 'shows',
 'a',
 'large',
 'amount',
 'of',
 'thrombogenesis',
 'in',
 'the',
 'femoropoplitea',
 'vein',
 'before',
 'thrombolysis',
 '.',
 'postoperative',
 'decreased'

In [52]:
from nltk import pos_tag
tags=pos_tag(words)

In [53]:
import nltk
from nltk import word_tokenize, pos_tag, ne_chunk
nltk.download('punkt')
nltk.download('maxent_ne_chunker')
nltk.download('words')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!


True

In [54]:
tokens = word_tokenize(captions)
tags = pos_tag(tokens)
ner_tree = ne_chunk(tags)
print(ner_tree)

(S
  coronal/JJ
  plain/NN
  computed/VBD
  tomography/JJ
  image/NN
  showing/VBG
  multiple/JJ
  large/JJ
  tumor/NN
  masses/NNS
  with/IN
  edge/NN
  enhancement/NN
  inside/IN
  the/DT
  abdominal/JJ
  cavity/NN
  and/CC
  liver/NN
  ./.
  axial/JJ
  source/NN
  image/NN
  from/IN
  an/DT
  intracranial/JJ
  magnetic/JJ
  resonance/NN
  angiogram/NN
  reveals/NNS
  abnormal/JJ
  arterial/JJ
  signal/NN
  elevation/NN
  in/IN
  the/DT
  left/NN
  more/JJR
  than/IN
  right/RB
  cavernous/JJ
  sinuses/NNS
  consistent/JJ
  with/IN
  a/DT
  carotid/NN
  cavernous/JJ
  fistula/NN
  ,/,
  as/IN
  indicated/VBN
  by/IN
  the/DT
  arrow/NN
  ./.
  the/DT
  apical/JJ
  height/NN
  ,/,
  homogeneity/NN
  ,/,
  and/CC
  the/DT
  thickness/NN
  of/IN
  mineral/JJ
  trioxide/NN
  aggregate/NN
  plug/NN
  cto/NN
  of/IN
  rca/NN
  (/(
  closure/NN
  in/IN
  the/DT
  2nd/CD
  segment/NN
  )/)
  venography/NN
  shows/VBZ
  a/DT
  large/JJ
  amount/NN
  of/IN
  thrombogenesis/NN
  in/IN
  the/DT


In [57]:
import spacy
from spacy import displacy
nlp=spacy.load("en_core_web_sm")
text="Apple is looking at buying UK startup for $ 1billion"
doc=nlp(text)
displacy.render(doc,style="ent",jupyter=True)

In [58]:
sentences=sentences[:2]

In [59]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100,binary=True)

In [60]:
sentences=["this is a NLP+CV project","Hi everyone NLP+CV"]

In [61]:
X=cv.fit_transform(sentences)
X.toarray()

array([[1, 0, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 0]])

In [62]:
cv.get_feature_names_out()

array(['cv', 'everyone', 'hi', 'is', 'nlp', 'project', 'this'],
      dtype=object)

In [63]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100,binary=True,ngram_range=(2,3))

In [64]:
X=cv.fit_transform(sentences)

In [65]:
X.toarray()

array([[1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0]])

In [66]:
cv.get_feature_names_out()

array(['cv project', 'everyone nlp', 'everyone nlp cv', 'hi everyone',
       'hi everyone nlp', 'is nlp', 'is nlp cv', 'nlp cv',
       'nlp cv project', 'this is', 'this is nlp'], dtype=object)

In [67]:
cv.vocabulary_

{'this is': 9,
 'is nlp': 5,
 'nlp cv': 7,
 'cv project': 0,
 'this is nlp': 10,
 'is nlp cv': 6,
 'nlp cv project': 8,
 'hi everyone': 3,
 'everyone nlp': 1,
 'hi everyone nlp': 4,
 'everyone nlp cv': 2}

In [83]:
sentences = ["This is the first document.", "This document is the second document.", "And this is the third one."]

In [84]:
sentences=sentences[:3]

In [85]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [86]:
tfidf=TfidfVectorizer(max_features=100)
X=tfidf.fit_transform(sentences).toarray()

In [87]:
sentences

['This is the first document.',
 'This document is the second document.',
 'And this is the third one.']

In [88]:
X

array([[0.        , 0.46941728, 0.61722732, 0.3645444 , 0.        ,
        0.        , 0.3645444 , 0.        , 0.3645444 ],
       [0.        , 0.7284449 , 0.        , 0.28285122, 0.        ,
        0.47890875, 0.28285122, 0.        , 0.28285122],
       [0.49711994, 0.        , 0.        , 0.29360705, 0.49711994,
        0.        , 0.29360705, 0.49711994, 0.29360705]])

In [89]:
tfidf.vocabulary_

{'this': 8,
 'is': 3,
 'the': 6,
 'first': 2,
 'document': 1,
 'second': 5,
 'and': 0,
 'third': 7,
 'one': 4}

In [90]:
!pip install gensim

In [91]:
from gensim.models import Word2Vec,KeyedVectors

In [95]:
import gensim.downloader as api
wv=api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [96]:
veec_king=wv["king"]
veec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [97]:
wv.most_similar("king")

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [98]:
wv.most_similar("car")

[('vehicle', 0.7821096181869507),
 ('cars', 0.7423831224441528),
 ('SUV', 0.7160962224006653),
 ('minivan', 0.6907036900520325),
 ('truck', 0.6735789775848389),
 ('Car', 0.6677608489990234),
 ('Ford_Focus', 0.667320191860199),
 ('Honda_Civic', 0.6626849174499512),
 ('Jeep', 0.651133120059967),
 ('pickup_truck', 0.6441438794136047)]

In [99]:
sentences

['This is the first document.',
 'This document is the second document.',
 'And this is the third one.']

In [100]:
words=[]
for i in range(len(sentences)):
    words_=nltk.word_tokenize(sentences[i])
    words.append(words_)

In [101]:
words

[['This', 'is', 'the', 'first', 'document', '.'],
 ['This', 'document', 'is', 'the', 'second', 'document', '.'],
 ['And', 'this', 'is', 'the', 'third', 'one', '.']]

In [103]:
cbow_model=Word2Vec(words,vector_size=10,min_count=1,sg=0)
skipgram_model=Word2Vec(words,vector_size=10,min_count=1,sg=1)

In [105]:
cbow_model.wv["document"]

array([ 0.07380296, -0.01532174, -0.04537598,  0.06552566, -0.04859179,
       -0.01815982,  0.0287764 ,  0.00991656, -0.0828639 , -0.09448527],
      dtype=float32)

In [107]:
cbow_model.wv.most_similar("document")

[('.', 0.5435577034950256),
 ('the', 0.3294057548046112),
 ('this', 0.2324611097574234),
 ('And', 0.03525553643703461),
 ('first', 0.03377028554677963),
 ('third', -0.17989817261695862),
 ('is', -0.21131564676761627),
 ('one', -0.3819473087787628),
 ('second', -0.5145915746688843),
 ('This', -0.5381641983985901)]

In [108]:
skipgram_model.wv["document"]

array([ 0.0737975 , -0.01532629, -0.04537274,  0.06553396, -0.04859476,
       -0.01816242,  0.02877441,  0.00991514, -0.08285948, -0.09447918],
      dtype=float32)

In [110]:
skipgram_model.wv.most_similar("document")

[('.', 0.5435900092124939),
 ('the', 0.3293773829936981),
 ('this', 0.23230676352977753),
 ('And', 0.03525340184569359),
 ('first', 0.03377976268529892),
 ('third', -0.1802682727575302),
 ('is', -0.21132346987724304),
 ('one', -0.38193345069885254),
 ('second', -0.5145905017852783),
 ('This', -0.5381653904914856)]